sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
before_install:
  - cd packages/react-anime
  - npm i
before_script:
  - npm prune
script:
  - npm run test
  - npm run build
after_success:
- npm run coverage
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
